# -*- coding: utf-8 -*-
"""Credit_Risk_Interpretability_vs_Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOSwztTptGCf7MeojttjQrhCXlwFj4oc

# Interpretable vs High‑Performance AI for Credit Risk Prediction
**Goal:** Compare *interpretability* (Decision Trees) vs *performance* (Neural Networks) on the Credit Card Default dataset (UCI / Kaggle).

This Colab is organized in 4 “weeks” that you can complete sequentially:
1. **Week 1:** Data understanding & EDA  
2. **Week 2:** Decision Tree (interpretability focus)  
3. **Week 3:** Logistic Regression + Neural Nets (performance focus)  
4. **Week 4:** Model comparison, ethics & report checklist

> Dataset: “Default of credit card clients” (30,000 rows, 23 features + target).

## Notebook Setup

Initialize the notebook environment, import essential libraries, and set up the dataset retrieval process from Kaggle.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay

import matplotlib.pyplot as plt

import seaborn as sns

from google.colab import userdata

# Set random seed for reproducibility
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

print("Libraries imported and random seed set.")

"""## Get the dataset into Colab"""

# --- Dataset Retrieval ---
KAGGLE_USERNAME = userdata.get('KAGGLE_USERNAME')
KAGGLE_KEY = userdata.get('KAGGLE_KEY')

os.environ['KAGGLE_USERNAME'] = KAGGLE_USERNAME
os.environ['KAGGLE_KEY'] = KAGGLE_KEY

# Ensure kaggle is installed and download dataset
!pip install -q kaggle
!kaggle datasets download -d uciml/default-of-credit-card-clients-dataset -p /content --force
!unzip -o /content/default-of-credit-card-clients-dataset.zip -d /content/dataset

print("\nContents of /content/dataset:")
!ls -lah /content/dataset

import os
from google.colab import userdata

# --- Dataset Retrieval ---
KAGGLE_USERNAME = userdata.get('KAGGLE_USERNAME')
KAGGLE_KEY = userdata.get('KAGGLE_KEY')

os.environ['KAGGLE_USERNAME'] = KAGGLE_USERNAME
os.environ['KAGGLE_KEY'] = KAGGLE_KEY

# Ensure kaggle is installed and download dataset
!pip install -q kaggle
!kaggle datasets download -d uciml/default-of-credit-card-clients-dataset -p /content --force
!unzip -o /content/default-of-credit-card-clients-dataset.zip -d /content/dataset

print("\nContents of /content/dataset:")
!ls -lah /content/dataset

"""## Week 1: Data Understanding & EDA

### Initial data loading
"""

df = pd.read_csv('/content/dataset/UCI_Credit_Card.csv')
print('Dataset Shape:', df.shape)
display(df.head())
df.info()

"""### Calculate class balance

"""

TARGET_COL = 'default.payment.next.month'

# Calculate class balance
print('Class Balance (0 = No Default, 1 = Default):')
balance = df[TARGET_COL].value_counts(normalize=True)
print(balance)

"""### Visualize credit limit distribution"""

# Visualize Credit Limit (LIMIT_BAL)
plt.figure(figsize=(10, 6))
plt.hist(df['LIMIT_BAL'], bins=50, color='skyblue', edgecolor='black')
plt.title('Distribution of Credit Limit (LIMIT_BAL)')
plt.xlabel('Credit Limit Amount')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### Visualize default Rates by Age, Education

"""

fig, axes = plt.subplots(1, 2, figsize=(20, 6))

# 1. Default Rate by Age Bin
age_bins = pd.cut(df['AGE'], bins=[20, 30, 40, 50, 60, 70, 80])
df.groupby(age_bins, observed=True)[TARGET_COL].mean().plot(kind='bar', ax=axes[0], color='salmon', edgecolor='black')
axes[0].set_title('Default Rate by Age Group')
axes[0].set_ylabel('Avg Default Rate')
axes[0].tick_params(axis='x', rotation=45)

# 2. Default Rate by Education
# (1=grad school, 2=university, 3=high school, 4=others, 5=unknown, 6=unknown)
df.groupby('EDUCATION')[TARGET_COL].mean().plot(kind='bar', ax=axes[1], color='lightgreen', edgecolor='black')
axes[1].set_title('Default Rate by Education Level')
axes[1].set_xlabel('Education (1=Grad, 2=Univ, 3=HS, 4+=Other)')

plt.tight_layout()
plt.show()

"""### Compute correlation heatmap of all numeric features in the dataset"""

# Correlation Heatmap
plt.figure(figsize=(16, 10))
corr_matrix = df.corr()
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap of Numeric Features')
plt.show()

"""## Week 2: RandomForest Classifier (Interpretability Focus)

### Prepare the data for modeling, then train and tune a RandomForestClassifier using GridSearchCV, including feature importance visualization.

"""

# Prepare feature matrix X and target vector y
X = df.drop(columns=[TARGET_COL, 'ID'])
y = df[TARGET_COL]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_SEED, stratify=y
)

# Define parameter grid
rf_param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [5, 10, None],
    'min_samples_leaf': [10, 20, 50],
    'max_features': ['sqrt']
}

# Initialize GridSearchCV
rf_grid = GridSearchCV(
    RandomForestClassifier(random_state=RANDOM_SEED, class_weight='balanced'),
    param_grid=rf_param_grid,
    scoring='f1',
    cv=3,
    n_jobs=-1,
    verbose=1
)

# Fit grid search
print('Starting GridSearchCV for RandomForestClassifier...')
rf_grid.fit(X_train, y_train)
print('Best params:', rf_grid.best_params_)

# Evaluate best model
best_rf = rf_grid.best_estimator_
y_pred_rf = best_rf.predict(X_test)

print('\nRandomForest Performance Metrics:')
print(f'  Accuracy : {accuracy_score(y_test, y_pred_rf):.4f}')

# Plot top 10 feature importances
rf_importances = pd.Series(best_rf.feature_importances_, index=X.columns).sort_values(ascending=False)

plt.figure(figsize=(10, 6))
rf_importances.head(10).plot(kind='barh', color='darkgreen')
plt.gca().invert_yaxis()
plt.title('Top 10 Feature Importances (Random Forest)')
plt.xlabel('Importance Score')
plt.ylabel('Features')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Week 3: Logistic Regression & Neural Networks (Performance Focus)

### Scale the features and train a Logistic Regression baseline, then implement and tune a Neural Network (MLPClassifier) using GridSearchCV to maximize predictive performance.

"""

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print('Features scaled successfully.')

# Logistic Regression baseline
lr_baseline = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=RANDOM_SEED)
lr_baseline.fit(X_train_scaled, y_train)
y_pred_lr = lr_baseline.predict(X_test_scaled)
print(f"\nLogistic Regression (Baseline) Accuracy : {accuracy_score(y_test, y_pred_rf):.4f}")

# Define parameter grid for MLP
mlp_param_grid = {
    'hidden_layer_sizes': [(50,), (100,), (50, 50)],
    'activation': ['relu', 'tanh'],
    'alpha': [0.0001, 0.05]
}

# Initialize and run GridSearchCV for MLP
mlp_grid = GridSearchCV(
    MLPClassifier(random_state=RANDOM_SEED, early_stopping=True, max_iter=500),
    param_grid=mlp_param_grid,
    scoring='f1',
    cv=3,
    n_jobs=-1,
    verbose=1
)

print('\nStarting GridSearchCV for MLPClassifier...')
mlp_grid.fit(X_train_scaled, y_train)
print('Best MLP params:', mlp_grid.best_params_)

# Extract best estimator and evaluate
best_mlp = mlp_grid.best_estimator_
y_pred_mlp = best_mlp.predict(X_test_scaled)
y_proba_mlp = best_mlp.predict_proba(X_test_scaled)[:, 1]

print('\nTuned MLP Performance Metrics:')
print(f'  Accuracy : {accuracy_score(y_test, y_pred_mlp):.4f}')

# Visualize results
plt.figure(figsize=(10, 6))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_mlp, cmap='Blues')
plt.title('Tuned MLP Confusion Matrix')
plt.tight_layout()
plt.show()

"""### Compare all the trained models"""

def summarize_results(y_true, y_pred, y_proba=None, model_name='Model'):
    metrics = {
        'Model': model_name,
        'Accuracy': accuracy_score(y_true, y_pred)
    }
    return metrics

# Consolidate results
dt_pred = best_rf.predict(X_test)

results_list = [
    summarize_results(y_test, y_pred_rf, None, 'Random Forest (Tuned)'),
    summarize_results(y_test, y_pred_lr, None, 'Logistic Regression (Balanced)'),
    summarize_results(y_test, y_pred_mlp, y_proba_mlp, 'MLP (Tuned GridSearch)')
]

comparison_df = pd.DataFrame(results_list).sort_values(by='Accuracy', ascending=False)
print('Final Model Comparison Table:')
display(comparison_df)

"""## Week 4: Final Report

### Goal
Think like a FinTech ML researcher

### Analysis Questions
Which model is:
 - Most accurate?
 - Most interpretable?
 - Would a bank prefer:
    - Slightly lower accuracy but explainability?
    - Black-box performance?
- What are the ethical risks of misclassification?

### Final Deliverables
 - Final Colab notebook
 - Mini research paper (6–8 pages)

"""