# -*- coding: utf-8 -*-
"""Research Spark Hub

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZjGPfYPZVyU7y4i-hyAvNM2Kuvm8y4c3
"""

# =========================================================
# CREDIT DEFAULT PREDICTION PROJECT
# FULLY FIXED FINAL VERSION + EVALUATION METRICS ADDED
# =========================================================

# THIS VERSION:
# ✅ Downloads dataset automatically
# ✅ Uses 3 DIFFERENT prediction methods
# ✅ Prompt 1 = simple guessing
# ✅ Prompt 2 = "acts like" Random Forest
# ✅ Prompt 3 = REAL Random Forest
# ✅ Shows actual answers
# ✅ No uploads needed
# ✅ No API needed
# ✅ Adds confusion matrix + precision/recall/F1 for Prompt 3
# ✅ Adds Logistic Regression baseline

# =========================================================
# 1. INSTALL LIBRARIES
# =========================================================
!pip install -q scikit-learn pandas

# =========================================================
# 2. IMPORT LIBRARIES
# =========================================================
import pandas as pd
import time

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

# =========================================================
# 3. LOAD UCI DATASET
# =========================================================

import os

csv_files = [f for f in os.listdir() if f.endswith(".csv")]

print("CSV files found:")
print(csv_files)

df = pd.read_csv(csv_files[0])

# Rename target column
if "default.payment.next.month" in df.columns:
    df.rename(
        columns={
            "default.payment.next.month": "DEFAULT"
        },
        inplace=True
    )

# Remove ID column
if "ID" in df.columns:
    df.drop(
        columns=["ID"],
        inplace=True
    )

print("Dataset Loaded Successfully ✅")


# =========================================================
# 4. DETECT TARGET COLUMN
# =========================================================

possible_targets = [
    "default.payment.next.month",
    "Default Payment Next Month",
    "default payment next month",
    "default",
    "DEFAULT",
    "Y",
    "target"
]

target_col = None

for col in possible_targets:

    if col in df.columns:
        target_col = col
        break

# fallback = last column
if target_col is None:

    target_col = df.columns[-1]

# rename target
df.rename(
    columns={
        target_col: "DEFAULT"
    },
    inplace=True
)

# =========================================================
# 5. REMOVE ID COLUMN IF EXISTS
# =========================================================

if "ID" in df.columns:

    df.drop(
        "ID",
        axis=1,
        inplace=True
    )

# =========================================================
# 6. FEATURES + TARGET
# =========================================================

# Make sure DEFAULT is numeric
df["DEFAULT"] = pd.to_numeric(df["DEFAULT"], errors="coerce")

# Remove any bad rows
df = df.dropna(subset=["DEFAULT"])

# Convert to integer labels
df["DEFAULT"] = df["DEFAULT"].astype(int)

X = df.drop(columns=["DEFAULT"])
y = df["DEFAULT"]

print("Features + Target Ready ✅")

# =========================================================
# 6b. DEBUG CHECK: CLASS BALANCE
# =========================================================
print("\n==============================")
print("DEBUG: CLASS BALANCE CHECK")
print("==============================")
print(df["DEFAULT"].value_counts())
print(df.shape)
print(df.head())

# =========================================================
# 7. TRAIN / TEST SPLIT
# =========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =========================================================
# 8. TRAIN REAL RANDOM FOREST
# =========================================================

print("\nTraining Random Forest...")

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

print(y_train.isna().sum())
print(y_train.head())

model.fit(
    X_train,
    y_train
)

print("Training Complete ✅")

# =========================================================
# 9. SELECT 2000 CLIENTS
# =========================================================

clients_to_predict = X_test.iloc[:2000]
actual_answers = y_test.iloc[:2000].tolist()

# =========================================================
# 10. PROMPT 1
# SIMPLE HUMAN-LIKE GUESSING
# =========================================================

print("\n================================================")
print("PROMPT 1")
print("================================================")

print("""
Predict whether these clients defaulted or not.

Use:
- General repayment behavior patterns.
""")

# SIMPLE HEURISTIC
start1 = time.time()
prompt1_predictions = []

for i in range(len(clients_to_predict)):

    row = clients_to_predict.iloc[i]

    # basic rule-based guess
    score = row.sum()

    if score > clients_to_predict.values.mean():

        prompt1_predictions.append(1)

    else:

        prompt1_predictions.append(0)

# SHOW RESULTS
for i, pred in enumerate(prompt1_predictions[:5]):

    result = (
        "DEFAULT"
        if pred == 1
        else "NO DEFAULT"
    )

    print(f"Client {i+1}: {result}")
time1 = time.time() - start1

# =========================================================
# 11. PROMPT 2
# ACT LIKE RANDOM FOREST
# =========================================================

print("\n================================================")
print("PROMPT 2")
print("================================================")

print("""
Act as a trained Random Forest classifier.

Use repayment history behavior
and payment patterns
to predict whether each client will default.
""")

# RANDOM-FOREST-LIKE HEURISTIC
start2 = time.time()
prompt2_predictions = []

for i in range(len(clients_to_predict)):

    row = clients_to_predict.iloc[i]

    # weighted heuristic
    score = row.mean()

    if score > clients_to_predict.mean().mean():

        prompt2_predictions.append(1)

    else:

        prompt2_predictions.append(0)

# SHOW RESULTS
for i, pred in enumerate(prompt2_predictions[:5]):

    result = (
        "DEFAULT"
        if pred == 1
        else "NO DEFAULT"
    )

    print(f"Client {i+1}: {result}")
time2 = time.time() - start2

# =========================================================
# 12. PROMPT 3
# REAL RANDOM FOREST
# =========================================================

print("\n================================================")
print("PROMPT 3")
print("================================================")

print("""
Actually use a Random Forest classifier.

Prioritize repayment history behavior
when predicting default risk.
""")

# REAL RF PREDICTIONS
start3 = time.time()

prompt3_predictions = model.predict(
    clients_to_predict
)

time3 = time.time() - start3

# SHOW RESULTS
for i, pred in enumerate(prompt3_predictions[:5]):

    result = (
        "DEFAULT"
        if pred == 1
        else "NO DEFAULT"
    )

    print(f"Client {i+1}: {result}")

# =========================================================
# 13. ACTUAL ANSWERS
# =========================================================

print("\n================================================")
print("ACTUAL ANSWERS")
print("================================================")

for i, ans in enumerate(actual_answers[:5]):

    result = (
        "DEFAULT"
        if ans == 1
        else "NO DEFAULT"
    )

    print(f"Client {i+1}: {result}")

# =========================================================
# 14. ACCURACY SUMMARY
# =========================================================

print("\n==============================")
print("SUMMARY")
print("==============================")

acc1 = 100 * sum(a == b for a, b in zip(prompt1_predictions, actual_answers)) / len(actual_answers)
acc2 = 100 * sum(a == b for a, b in zip(prompt2_predictions, actual_answers)) / len(actual_answers)
acc3 = 100 * sum(a == b for a, b in zip(prompt3_predictions, actual_answers)) / len(actual_answers)

print(f"Prompt 1 Accuracy: {acc1:.2f}%")
print(f"Prompt 2 Accuracy: {acc2:.2f}%")
print(f"Prompt 3 Accuracy: {acc3:.2f}%")

print()

print(f"Prompt 1 Avg Time per Client: {time1/len(actual_answers):.8f} sec")
print(f"Prompt 2 Avg Time per Client: {time2/len(actual_answers):.8f} sec")
print(f"Prompt 3 Avg Time per Client: {time3/len(actual_answers):.8f} sec")

# =========================================================
# 15. NEW: CONFUSION MATRIX + PRECISION / RECALL / F1
#     FOR PROMPT 3 (RANDOM FOREST)
# =========================================================

print("\n==============================")
print("CONFUSION MATRIX (PROMPT 3 / RANDOM FOREST)")
print("==============================")

tn, fp, fn, tp = confusion_matrix(actual_answers, prompt3_predictions).ravel()
precision = precision_score(actual_answers, prompt3_predictions)
recall = recall_score(actual_answers, prompt3_predictions)
f1 = f1_score(actual_answers, prompt3_predictions)

print(f"True Negatives (TN):  {tn}")
print(f"False Positives (FP): {fp}")
print(f"False Negatives (FN): {fn}")
print(f"True Positives (TP):  {tp}")
print()
print(f"Precision (default class): {precision:.4f}")
print(f"Recall (default class):    {recall:.4f}")
print(f"F1-score (default class):  {f1:.4f}")

# =========================================================
# 16. NEW: LOGISTIC REGRESSION BASELINE
# =========================================================

print("\n==============================")
print("LOGISTIC REGRESSION BASELINE")
print("==============================")

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

logreg_predictions = log_reg.predict(clients_to_predict)

logreg_acc = 100 * sum(a == b for a, b in zip(logreg_predictions, actual_answers)) / len(actual_answers)

print(f"Logistic Regression Accuracy: {logreg_acc:.2f}%")

# Optional: confusion matrix + precision/recall/F1 for Logistic Regression too,
# useful if you want to compare class-level behavior against Random Forest.
lr_tn, lr_fp, lr_fn, lr_tp = confusion_matrix(actual_answers, logreg_predictions).ravel()
lr_precision = precision_score(actual_answers, logreg_predictions)
lr_recall = recall_score(actual_answers, logreg_predictions)
lr_f1 = f1_score(actual_answers, logreg_predictions)

print(f"TN={lr_tn}, FP={lr_fp}, FN={lr_fn}, TP={lr_tp}")
print(f"Precision: {lr_precision:.4f}")
print(f"Recall: {lr_recall:.4f}")
print(f"F1-score: {lr_f1:.4f}")